### ISSUE TITLE
Drop text-rendering/font-smoothing

### ISSUE THREAD

**Issue by GrimLink** [n-elements/core#149]
Using text-rendering/font-smoothing as default is a bad practice to make text look better.
There enough articles to explaining why. 

But in short this should only be used if you need it for white text on dark backgrounds.
But it is better to use a lighter font weight instead.

**Comment by equinusocio** [comment]
Hi @GrimLink, can you share some resources about this?

**Comment by GrimLink** [comment]
@equinusocio no problem.

These article are both mentioned on the  https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth page.

- https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/
- https://www.zachleat.com/web/font-smooth/

But there are more articles found on the reasons.

As stated the spec has also been removed and is now none standard.
And it is better to just use a lighter font weight instead of this for.
Which has also better support than this spec.

**Comment by equinusocio** [comment]
We do this to make font rendering consistent between firefox and Safari/Chrome on Mac (as I know this property is not applied on Windows).

With **grayscale** smoothing:

<img width="1569" alt="grayscale" src="https://user-images.githubusercontent.com/10454741/84888768-16aa5280-b098-11ea-870d-0e7608a164c9.png">


With **auto** smoothing:

<img width="1569" alt="auto" src="https://user-images.githubusercontent.com/10454741/84888799-25910500-b098-11ea-84d1-1f6b17e68333.png">

As with the auto smoothing Firefox on mac will render thinner text compared with Safari and Chrome. While with the grayscale option the font-weight is the same on both browsers. Is this wrong?

**Comment by GrimLink** [comment]
I have to disagree on that screenshot.
I just made this screenshot of github.

![Screenshot 2020-06-17 at 21 20 12](https://user-images.githubusercontent.com/4387541/84940718-83e1d600-b0e0-11ea-93a5-06ffff30438f.jpg)

Github is also not using font-smoothing in any form.
As you can see the text looks the same using system fonts.
It might be different if you are using a custom font.

This is a choice a develop should make not a default style.
It gives a bad practise to develops who don't take time investing in typography and accessibility.
Understanding what this does CSS property does well and what not. 

Many CSS framework still ship it but at least as option to turn off.
And some CSS framework even removed it from altogether.

**Comment by equinusocio** [comment]
I don't understand why Github doesn't have this issue. If you open this fiddle with Safari and switch off the font smoothing you see the difference even with the system font.

https://jsfiddle.net/vg8uqszx/

That's weird, but yes this is something we can remove from the core.

**Comment by GrimLink** [comment]
Not yet but planning to 😉 and like what you did with this project.

**Comment by equinusocio** [comment]
> Not yet but planning to 😉 and like what you did with this project.

If you’ll use it, please and your site at the end of this file via PR:

https://github.com/n-elements/website/blob/master/src/docs/getting-started/Introduction.mdx
