### ISSUE TITLE
FIX: content-box on details children

### ISSUE THREAD

**Issue by GrimLink** [n-elements/core#151]
If the box-sizing is set to inherit from the html.
The child elements of a html details element will receive content-box as inherit from the details.

See PR #151 for the possible solution.

**Comment by equinusocio** [comment]
> The child elements of a html details element will receive content-box as inherit from the details.

We want to discuss this 👆. Why do you think this is a bug?

This is intentional since it allows every element to inherit box-sizing from the global one (content-box). This is valid also for elements inside `details` that are not handled by the library (excluding the entrance animation)

**Comment by GrimLink** [comment]
You make a valid point and I would agree.
If this bug on the details element did not exist.

But if I wanted to use anything that responds as border-box.
And it is suddenly a content-box in the `<details>` element would give a weird experience.
And for that reason it sadly now is better to set it directly.
Or make it and option?

At the moment this has been accepted by some frameworks as the acceptable solution.
[For example Bootstrap to mention one](https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap.css#L34).

**Comment by equinusocio** [comment]
> But if I wanted to use anything that responds as border-box.
And it is suddenly a content-box in the <details> element would give a weird experience.

Can you share a use case for this? It could help me understand the issue.

**Comment by GrimLink** [comment]
> Can you share a use case for this? It could help me understand the issue.

Sure see this https://jsfiddle.net/GrimLink/b2hktj93/11/ for an example with a card and input element.

As you can see the input is bigger in a details element since the padding is not part of the width.
Since the children are back to content-box sizing in a details element.

**Comment by equinusocio** [comment]
Ok, this happens only on Chrome/Webkit. Firefox handle this correctly.

**Comment by equinusocio** [comment]
What do you think if we leave the global box-sizing as a custom property, and make all the elements inside the `details` using it? Something like this:


```css
html {
	box-sizing: var(--ne-global-box-sizing);
}

*,
*::before,
*::after {
	box-sizing: inherit;
}

details * {
	box-sizing: var(--ne-global-box-sizing);
}
```

This should avoid the bug on Chrome/Safari without compromising other elements.

**Comment by GrimLink** [comment]
Yes that is a great solution
